"""unique field to file_name model

Revision ID: 846a8812dce2
Revises: caf578bcbead
Create Date: 2025-03-03 16:31:14.810157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '846a8812dce2'
down_revision: Union[str, None] = 'caf578bcbead'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'transcription', ['file_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transcription', type_='unique')
    # ### end Alembic commands ###
