"""add audio_url model-schemas

Revision ID: caf578bcbead
Revises: 04b6c85c62f3
Create Date: 2025-03-03 15:25:05.389830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caf578bcbead'
down_revision: Union[str, None] = '04b6c85c62f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcription', sa.Column('audio_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcription', 'audio_url')
    # ### end Alembic commands ###
